// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzwdzsijkpzatnsfmcjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6d2R6c2lqa3B6YXRuc2ZtY2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDcyMjYsImV4cCI6MjA2NTEyMzIyNn0.HMK0L-P4bFBW6UNZ0_q-wvUY3MKRbdFEivLkGzR0v1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);